# Kimi K2.6 Model Config

defaults:
  - ../../models/image_encoder@model.image_encoder: moon_vit_3d
  - ../../models/image_projector@model.image_projector: patch_merger_adapter
  - ../../models/kimi_k2@model.foundation: kimi_k2
  - _self_

model:
  model_type: kimi_k2_6
  loss_func: ${loss_func:default}
  image_encoder:
    model_spec: ["loongforge.models.encoder.moon_vision_models.moon_vision_layer_spec",
                 "get_moon_vision_model_layer_with_te_spec"]
  image_projector:
    model_spec: ["loongforge.models.encoder.moon_vision_models.moon_vision_layer_spec",
     "get_adapeter_layer_with_te_spec"]
  vision_token_id: 163603
