_target_: loongforge.models.diffusion.WanConfig
num_layers: 40
hidden_size: 5120
ffn_hidden_size: 13824
text_dim: 4096
num_attention_heads: 40
latent_in_channels: 4
latent_out_channels: 8
latent_patch_size: [1, 2, 2]
latent_space_scale: 0.5
latent_time_scale: 1.0
vae_temporal_compress: 4
vae_spatial_compress: 8
has_image_input: True
clip_num_image_tokens: 257
freq_dim: 256
in_dim: 36
out_dim: 16
norm_epsilon: 1e-6
require_clip_embedding: True
has_image_pos_emb: False
model_type: "wan2_1_i2v"
attention_dropout: 0.0
hidden_dropout: 0.0
use_fused_wan_rope: True
